### ISSUE TITLE
Won't Start, "dns.js" Error

### ISSUE THREAD

**Issue by torridgristle** [stuffmatic/fSpy#36]
I used the Win64 build, not the installer, and when I try to open fSpy nothing appears. When I run it from PowerShell I get this:

dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13

I suspect it may be related to not having an internet connection at the time because now that I'm at the library with an internet connection it's not giving me this error. I don't think this should be happening at all though, can't see what having an internet connection has to do with this; it should all be done on the local machine, right?

**Comment by stuffmatic** [comment]
Seems to be a [bug in Electron](https://github.com/electron/electron/issues/14117). The next fSpy release will use the most recent version of electron, so let's hope that fixes this issue.
