### ISSUE TITLE
Crash when trying to run fspy: Javascript error in the main proccess Mac OS

### ISSUE THREAD

**Issue by nixoye** [stuffmatic/fSpy#94]
Whenever I try to run fspy on mac os I get this error:

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot set property 'domain' of null
at EventEmitter.init (events.js:63:15)
at EventEmitter (events.js:28:21)
at Object.<anonymous> (/Applications/fSpy.app/Contents/Resources/electron.asar/browser/api/screen.js:7:14)
at Object.<anonymous> (/Applications/fSpy.app/Contents/Resources/electron.asar/browser/api/screen.js:19:3)
at Module._compile (module.js:642:30)
at Object.Module._extensions..js (module.js:653:10)
at Module.load (module.js:561:32)
at tryModuleLoad (module.js:504:12)
at Function.Module._load (module.js:496:3)
at Module.require (module.js:586:17)
```

**Comment by ironcladmerc** [comment]
had the same issue first time I ran it, I just tried again and it works the 2nd time
